version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic-config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash-config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    configs:
      - source: kibana-config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:

  elastic-config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash-config:
    file: ./logstash/config/logstash.yml
  logstash-pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana-config:
    file: ./kibana/config/kibana.yml

networks:
  elk:
    driver: overlay
